import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import FirecrawlApp from '@mendable/firecrawl-js';
import { generateObject } from 'ai';
import { createDeepSeek } from '@ai-sdk/deepseek';
import { z } from 'zod';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const API_KEY = process.env.DEEPSEEK_API_KEY;
const FIRECRAWL_API_KEY = process.env.FIRECRAWL_API_KEY;

// Setup DeepSeek provider
const deepseek = createDeepSeek({
  apiKey: API_KEY,
});

async function run() {
  if (!API_KEY || !FIRECRAWL_API_KEY) {
    console.error('Missing API keys in .env');
    return;
  }

  const app = new FirecrawlApp({ apiKey: FIRECRAWL_API_KEY });
  console.log('Searching for Somali political news across multiple queries...');

  const queries = [
    "Somalia politics breaking news",
    "Somaliland elections and politics",
    "Puntland security and politics"
  ];

  // 1. Concurrent multi-query search
  const searchPromises = queries.map(q => app.search(q, { limit: 10 }).catch(e => {
    console.error(`Search failed for '${q}':`, e.message);
    return null;
  }));
  
  const searchResultsArray = await Promise.all(searchPromises);
  
  // 2. Pool and deduplicate URLs
  const uniqueUrls = new Set();
  const pooledItems = [];
  
  for (const results of searchResultsArray) {
    if (!results) continue;
    const items = results.web ? results.web : results.data;
    for (const item of items) {
      if (!uniqueUrls.has(item.url)) {
        uniqueUrls.add(item.url);
        pooledItems.push(item);
      }
    }
  }

  console.log(`Found ${pooledItems.length} unique articles from search.`);

  // Take up to 15 to process
  const targetItems = pooledItems.slice(0, 15);
  const finalArticles = [];

  // 3. Concurrent Scrape + DeepSeek processing
  const processPromises = targetItems.map(async (item, i) => {
    try {
      console.log(`[${i+1}] Scraping: ${item.url}`);
      
      let fullText = item.description || "";
      try {
        const scrapeResult = await app.scrapeUrl(item.url, { formats: ['markdown'] });
        if (scrapeResult && scrapeResult.markdown) {
          fullText = scrapeResult.markdown.substring(0, 3000);
        }
      } catch (e) {
        console.log(`[${i+1}] Scrape failed, falling back to summary. (${e.message})`);
      }

      const rawText = `Title: ${item.title}\nSource: ${item.url}\nContent: ${fullText}`;

      console.log(`[${i+1}] Generating strict JSON with DeepSeek...`);
      
      const { object } = await generateObject({
        model: deepseek('deepseek-chat'),
        system: 'You are an expert editorial editor for East African news. Given this scraped web text about Somali politics, output structured data according to the schema.',
        prompt: rawText,
        schema: z.object({
          summary: z.string().describe('A 1 sentence editorial dek'),
          ai_summary_points: z.array(z.string()).length(4).describe('Exactly 4 string bullets of key facts'),
          category: z.enum(['Politics', 'Economy', 'Security', 'Society', 'Regional']),
          full_article: z.string().describe('A detailed, multi-paragraph editorial news story expanding on the facts with professional journalism style, at least 3-4 paragraphs long, separated by two newlines.')
        })
      });

      console.log(`[${i+1}] Success!`);
      
      return {
        id: `real-news-${i}-${Date.now()}`,
        title: item.title,
        slug: item.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
        summary: object.summary,
        content: object.full_article,
        source: new URL(item.url).hostname,
        country: 'Somalia', // Simplified for now
        category: object.category,
        published_at: new Date().toISOString(),
        update_batch: new Date().getHours() < 12 ? 'morning' : 'afternoon',
        featured: false, // Set later
        ai_summary_points: object.ai_summary_points
      };

    } catch (err) {
      console.error(`[${i+1}] Failed to process:`, err.message);
      return null;
    }
  });

  const results = await Promise.allSettled(processPromises);
  
  for (const res of results) {
    if (res.status === 'fulfilled' && res.value) {
      finalArticles.push(res.value);
    }
  }

  // Cap at 10 and set featured
  const limitedArticles = finalArticles.slice(0, 10);
  if (limitedArticles.length > 0) {
    limitedArticles[0].featured = true;
  }

  console.log(`Successfully generated ${limitedArticles.length} perfect articles.`);
  
  const output = `// Auto-generated by fetchNews.js (Firecrawl + DeepSeek + Zod)\n\nexport interface Article {\n  id: string;\n  title: string;\n  slug: string;\n  summary: string;\n  content: string;\n  source: string;\n  country: string;\n  category: string;\n  published_at: string;\n  update_batch: 'morning' | 'afternoon';\n  featured: boolean;\n  ai_summary_points: string[];\n}\n\nexport const newsArticles: Article[] = ${JSON.stringify(limitedArticles, null, 2)};\n`;

  const outPath = path.join(__dirname, '../src/data/newsData.ts');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output);
  console.log('Wrote to src/data/newsData.ts');
}

run();
