import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Parser from 'rss-parser';
import { generateObject } from 'ai';
import { createDeepSeek } from '@ai-sdk/deepseek';
import { z } from 'zod';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const API_KEY = process.env.DEEPSEEK_API_KEY;

const deepseek = createDeepSeek({
  apiKey: API_KEY,
});

async function run() {
  console.log('Fetching latest social/news signals from Google News RSS (<24 hours old)...');
  
  try {
    const parser = new Parser();
    const feed = await parser.parseURL('https://news.google.com/rss/search?q=Somalia+when:1d&hl=en-US&gl=US&ceid=US:en');
    
    if (feed.items.length === 0) {
      console.log('No news found.');
      return;
    }

    const topItems = feed.items.slice(0, 5).map(item => ({
      title: item.title,
      link: item.link,
      date: item.pubDate,
      snippet: item.contentSnippet || ''
    }));

    const rawText = JSON.stringify(topItems, null, 2);

    console.log('Requesting DeepSeek to generate viral social media snapshots...');
    
    const { object } = await generateObject({
      model: deepseek('deepseek-chat'),
      system: 'You are an AI crawling social media and news feeds for East African intelligence. Given these raw RSS items about Somalia, extract the top 5 updates into short, punchy social-media style updates (like tweets). Assign a fake source network to each.',
      prompt: rawText,
      schema: z.object({
        updates: z.array(z.object({
          source: z.enum(['X', 'Facebook', 'News']),
          author: z.string().describe('e.g. @SomaliaUpdates or BBC News Africa'),
          content: z.string().describe('A short, 1-2 sentence urgent update, max 150 chars'),
          link: z.string().describe('The URL to the story'),
          published_at: z.string().describe('ISO date string')
        }))
      })
    });

    // Archiving logic for social feeds
    const outPath = path.join(__dirname, '../src/data/socialFeed.ts');
    let existingFeed = [];
    
    try {
      if (fs.existsSync(outPath)) {
        const fileContent = fs.readFileSync(outPath, 'utf-8');
        const match = fileContent.match(/export const socialFeed: SocialPost\[\] = (\[.*\]);/s);
        if (match && match[1]) {
          existingFeed = JSON.parse(match[1]);
        }
      }
    } catch (e) {
      console.error('Could not parse existing social feed, starting fresh.');
    }

    // Add unique IDs
    const newFeed = object.updates.map((u, i) => ({
      ...u,
      id: `social-${Date.now()}-${i}`
    }));

    let combinedFeed = [...newFeed, ...existingFeed];
    // Cap at 20 updates
    combinedFeed = combinedFeed.slice(0, 20);

    const output = `// Auto-generated by fetchSocial.js (RSS + DeepSeek)\n\nexport interface SocialPost {\n  id: string;\n  source: 'X' | 'Facebook' | 'News';\n  author: string;\n  content: string;\n  link: string;\n  published_at: string;\n}\n\nexport const socialFeed: SocialPost[] = ${JSON.stringify(combinedFeed, null, 2)};\n`;

    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, output);
    console.log(`Success! Wrote ${combinedFeed.length} social updates to ${outPath}`);
  } catch (error) {
    console.error('Fetch failed:', error.message);
  }
}

run();
