// Auto-generated by fetchSocial.js (RSS + DeepSeek)

export interface SocialPost {
  id: string;
  source: 'X' | 'Facebook' | 'News';
  author: string;
  content: string;
  link: string;
  published_at: string;
}

export const socialFeed: SocialPost[] = [
  {
    "source": "News",
    "author": "UNESCO",
    "content": "UNESCO Youth for Peace grantee uses digital storytelling to strengthen social cohesion in Somalia.",
    "link": "https://news.google.com/rss/articles/CBMivwFBVV95cUxOMzBEOXpUSFhVdzV1bjRqblBWMzg4bV9wMFFoOUNaUk0xSnhLNTJULUlZN29LdHhubVJ4R0VpYVBxMUlUS1FQMTM2Zm0wTFdhZnlScU1vSHJLMzRzNm9SdmdsZWYyN3AxUE5tSU5fanRIeUQ5NVhEbFl6RGxGZkpRLUZ5b1FlLUQ1aWc2UGFZSGlpQ1NwVTgydXgyVnIwc0xodWV6bEo1MnBBWUZkdkFXUkZyck9ITll5WmNMbXFWZw?oc=5",
    "published_at": "2026-07-06T09:53:38Z",
    "id": "social-1783349471942-0"
  },
  {
    "source": "X",
    "author": "@EUNAVFOR",
    "content": "Operation ATALANTA secures bulk carrier following pirate attack off Somalia.",
    "link": "https://news.google.com/rss/articles/CBMioAFBVV95cUxOWGp4UnEyNXJtRDZ4cGxOX0hEa2lJSzJmQkV1bFZIckplc2ZoZGlWdEpjWTQ1ei0xUWJkTGRGcEVHNXdyOGlzUU1lUXJzUmJ1YWNHQlNNZDZIaG12eFZoMnFuek51eDg2UlpEZzBHbzM1WUlIbDFBREpUZTR2cEpXX0xWSHBSLUdNbklZVVdUMnlHaUkxdVdqV3FJQmtMQk9n?oc=5",
    "published_at": "2026-07-06T10:16:25Z",
    "id": "social-1783349471942-1"
  },
  {
    "source": "News",
    "author": "Genocide Watch",
    "content": "Somalia peacekeeping mission at risk as US blocks UN support, sources say.",
    "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPZ3RiOVRiTGxBM181UEx0clVvaEplWnRuSjhRM1dsV3JCNDQtcGxKMW40c2FBVzhpV2xUbGtUMVlhMlZNMkxNVmp0QWpmT2QxUnliNHpqaFZ1S2tDQmZhWklWeHUyRjZpWkg4SVdrbUt1TW5aYllDbFRKNUIxdDlsMlBQcS1zREhzc1dBdEFyMXI2c1RoemI5Qzlfd19GVWUtLUdNYTE2ZkgtMUlPQnplVUpPY3E?oc=5",
    "published_at": "2026-07-05T18:52:32Z",
    "id": "social-1783349471942-2"
  },
  {
    "source": "X",
    "author": "@SomaliGuardian",
    "content": "Somalia’s president slams Israel as an ‘evil’, war-mongering state.",
    "link": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxOX21NcWdoU0FKd3RYdXJJb3lTb2xWY2VfMTFXRFpTUFl4Z0hGc3VRRGNCOHEzUkR3R1BJeFVQNzBPUVZrV3RBUzBXcEVjNFNvb2ZqXy1vM1hCc0hMUnpGdWRNS1FvSkJBc3dCY0xrOHNhOUYwTGNpQ2JNd3l6NXRYekZmVVRQVXR2WHJnOHhIZThfQkNaU180dzltUF81WUY1VGlQUmF1ZzA?oc=5",
    "published_at": "2026-07-06T09:52:08Z",
    "id": "social-1783349471942-3"
  },
  {
    "source": "News",
    "author": "Garowe Online",
    "content": "Foreign troop drawdown begins in Somalia amid security and funding concerns.",
    "link": "https://news.google.com/rss/articles/CBMivAFBVV95cUxOMDFZLXBpR3U0ZDdMOUkxLUJUbDRMcXRUcmcwVDJyNW5OSFY3ZWVndGJOOU92dklMSHpscW5tRmg2dEV4aWlIaDNVNkZyVUtRZTZZNUJfYVZfYklXajlIQXV2b1lka0UyaTlseFRoTXhVUENTNFVfZ05jV1pfNmxzbTc2cExwcE1fa1RQSy1iS1R6YTRUQnZDaFZHWkVxc0tGZzgxU3RXS3JYVzZkNkQ4aTVVNzBwNURQMFVNYQ?oc=5",
    "published_at": "2026-07-06T08:43:38Z",
    "id": "social-1783349471942-4"
  },
  {
    "source": "News",
    "author": "Genocide Watch",
    "content": "Somalia peacekeeping mission at risk as US blocks UN support, sources say.",
    "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPZ3RiOVRiTGxBM181UEx0clVvaEplWnRuSjhRM1dsV3JCNDQtcGxKMW40c2FBVzhpV2xUbGtUMVlhMlZNMkxNVmp0QWpmT2QxUnliNHpqaFZ1S2tDQmZhWklWeHUyRjZpWkg4SVdrbUt1TW5aYllDbFRKNUIxdDlsMlBQcS1zREhzc1dBdEFyMXI2c1RoemI5Qzlfd19GVWUtLUdNYTE2ZkgtMUlPQnplVUpPY3E?oc=5",
    "published_at": "2026-07-05T18:52:32Z",
    "id": "social-1783325278863-0"
  },
  {
    "source": "News",
    "author": "Amani Africa",
    "content": "US plan to unplug UN Support Office in Somalia may break African Union peace operation.",
    "link": "https://news.google.com/rss/articles/CBMi4AFBVV95cUxQYmw1d1JmNFNTSmlFZF92akxFQW55VXJwNHhpU1JXTHRlRmVGdXFjaXpCTGJXeGJtYnZCSGJZWDdLaUhFQ1BMdzNBUGRMMWZRamwyQnFoY1BNTXJxXzU5TFN6eHVOS2ozSGcwVG44Q1JUaHhWdUFRRXU0QWxUa2Y2dkVsMmFJeFdZNmRHM1dQSUVKejdnSVVoRUNfTkw1Z21JWmFBVm52Vjk5SFp5X1ZJNXJEYVNiWHA2eWxxdVljU1JrbFBDallrUTh5NFlFWEE4Z1UyaENGWTRkaS1qS1E3ZA?oc=5",
    "published_at": "2026-07-05T08:09:44Z",
    "id": "social-1783325278863-1"
  },
  {
    "source": "X",
    "author": "@theins_press",
    "content": "Trump's policies are making Somali piracy great again, says report.",
    "link": "https://news.google.com/rss/articles/CBMiUEFVX3lxTE9tV0lNSC1yajM3ZVNpdGlPOWFjSUlTR043ZXo0TzdhbDJJR0J6Zk5YVGFEeFI4dnlMQ2kxb2x6bjBhUU1XcW1BTm8yenFwaHc5?oc=5",
    "published_at": "2026-07-06T06:14:50Z",
    "id": "social-1783325278863-2"
  },
  {
    "source": "News",
    "author": "AOL.com",
    "content": "Minnesota man captured in Somalia over $250M child nutrition fraud scheme.",
    "link": "https://news.google.com/rss/articles/CBMijAFBVV95cUxOdXRHUVF5MEMySzdSNTBUR1NycFdvcVZ2VEFKekhSZnBrNFRESnR3WTBwZnRJLVNfZ3VSUTVYZnBXUHg3ME9mTGViV1VtcTdlVDZKREMzRTg0V3RlNGdtTjN5S1JJbHRFQzJ6T2JnU3pSQlNDb2ExaklDZmZPcmtDWGFXQmtRd2xHVWxBeA?oc=5",
    "published_at": "2026-07-06T00:54:34Z",
    "id": "social-1783325278863-3"
  },
  {
    "source": "Facebook",
    "author": "Hiiraan Online",
    "content": "Somalia to issue new modern passport in October 2026.",
    "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxNRVg2aFdMQVBDeU9OYmdMR2x0WTdXaGlmT2hzLWNPalI0R0I2X0lHUm5aNWVLWUtOWVZhbXF2TWtROTh4elhHUEpnVWd1YkxPSEU3M1N6NERNMEdqMkg2SFVvQVZXLThqTHZweHVWOGVTdTRNSWVmdVZFSDBtWXJtNHY3UC0yY3ZuOEZGVXpmcXc1QmZJb3Y1R0hfbzJoU01IWkQ3YWFn?oc=5",
    "published_at": "2026-07-06T02:49:39Z",
    "id": "social-1783325278863-4"
  },
  {
    "source": "News",
    "author": "Genocide Watch",
    "content": "Somalia peacekeeping mission at risk as US blocks UN support.",
    "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPZ3RiOVRiTGxBM181UEx0clVvaEplWnRuSjhRM1dsV3JCNDQtcGxKMW40c2FBVzhpV2xUbGtUMVlhMlZNMkxNVmp0QWpmT2QxUnliNHpqaFZ1S2tDQmZhWklWeHUyRjZpWkg4SVdrbUt1TW5aYllDbFRKNUIxdDlsMlBQcS1zREhzc1dBdEFyMXI2c1RoemI5Qzlfd19GVWUtLUdNYTE2ZkgtMUlPQnplVUpPY3E?oc=5",
    "published_at": "2026-07-05T18:52:32Z",
    "id": "social-1783302664702-0"
  },
  {
    "source": "News",
    "author": "Amani Africa",
    "content": "US plan to unplug UN Support Office in Somalia may break AU peace operation.",
    "link": "https://news.google.com/rss/articles/CBMi4AFBVV95cUxQYmw1d1JmNFNTSmlFZF92akxFQW55VXJwNHhpU1JXTHRlRmVGdXFjaXpCTGJXeGJtYnZCSGJZWDdLaUhFQ1BMdzNBUGRMMWZRamwyQnFoY1BNTXJxXzU5TFN6eHVOS2ozSGcwVG44Q1JUaHhWdUFRRXU0QWxUa2Y2dkVsMmFJeFdZNmRHM1dQSUVKejdnSVVoRUNfTkw1Z21JWmFBVm52Vjk5SFp5X1ZJNXJEYVNiWHA2eWxxdVljU1JrbFBDallrUTh5NFlFWEE4Z1UyaENGWTRkaS1qS1E3ZA?oc=5",
    "published_at": "2026-07-05T08:09:44Z",
    "id": "social-1783302664702-1"
  },
  {
    "source": "News",
    "author": "The HALO Trust",
    "content": "Demining and risk education ongoing in Somalia.",
    "link": "https://news.google.com/rss/articles/CBMiakFVX3lxTE1WeUZwWWlwUm5ZdjZnTTJZYzRNMVNURHEzVzFmWlNkQ3d4MnB3ZlpISHE2cUs4T2pZcE1fSEdKUjl6eS1ndXNxVVRJemFBQjZvcTZYWTVtOUg1ZUVNYS1xeXNCUkVPblpFdkE?oc=5",
    "published_at": "2026-07-05T06:26:04Z",
    "id": "social-1783302664702-2"
  },
  {
    "source": "X",
    "author": "@SomaliGuardian",
    "content": "Puntland bans Turkish fishing firm SOMTURK.",
    "link": "https://news.google.com/rss/articles/CBMiogFBVV95cUxQTXI2YXlIQVJ0MDluVUhlVzU1RHozX2xDOTY4N0p0WDg1TTZHQ1ZPUkQ4ZEgtdDJEdmdINHZycjRkcUFvbWFxQkE4UFpLTVFjNlg1Mkw5WG5kVlcxaXFyTnoxWTJCTm5VZUdNS1FBQnRUZ3VxNjRkQXNYZGJlWlM5RjF2dl9FeTltb2N3Qk5oRjIyWlg5MElOMVlUc2tWS2N6VWc?oc=5",
    "published_at": "2026-07-05T14:57:06Z",
    "id": "social-1783302664702-3"
  },
  {
    "source": "Facebook",
    "author": "Hiiraan Online",
    "content": "Somali President meets St. Louis Park Mayor Nadia Mohamed in Mogadishu.",
    "link": "https://news.google.com/rss/articles/CBMivAFBVV95cUxPS19RQnBUSEFrVURVZlZUYk0xTERkUkhRYjhmRDlKRXhEclp6M0FrSE05b3NZSl9oTHJ4RVNBd0lUUjVkbjFXRndFejlyRGFXSVpHTjctZXZvMDVhZktVUkY3bTAtZ2pNaC1VbmhlTmJsdi12MGhGZkt5Z1kyMnctcklnLWtGT2ZleUFNM0lEQlhsQmRIUVRiUElTbTc5XzBTeUVwNmNkWWYzOEtVSDlhR0FpVU1zWlI0Um9hWA?oc=5",
    "published_at": "2026-07-06T00:05:10Z",
    "id": "social-1783302664702-4"
  },
  {
    "source": "News",
    "author": "Genocide Watch",
    "content": "Somalia peacekeeping mission at risk as US blocks UN support, sources say.",
    "link": "https://news.google.com/rss/articles/CBMitAFBVV95cUxPZ3RiOVRiTGxBM181UEx0clVvaEplWnRuSjhRM1dsV3JCNDQtcGxKMW40c2FBVzhpV2xUbGtUMVlhMlZNMkxNVmp0QWpmT2QxUnliNHpqaFZ1S2tDQmZhWklWeHUyRjZpWkg4SVdrbUt1TW5aYllDbFRKNUIxdDlsMlBQcS1zREhzc1dBdEFyMXI2c1RoemI5Qzlfd19GVWUtLUdNYTE2ZkgtMUlPQnplVUpPY3E?oc=5",
    "published_at": "2026-07-05T18:50:30Z",
    "id": "social-1783284254430-0"
  },
  {
    "source": "News",
    "author": "Amani Africa",
    "content": "US plan to unplug UN Support Office in Somalia may break African Union peace operation.",
    "link": "https://news.google.com/rss/articles/CBMi4AFBVV95cUxQYmw1d1JmNFNTSmlFZF92akxFQW55VXJwNHhpU1JXTHRlRmVGdXFjaXpCTGJXeGJtYnZCSGJZWDdLaUhFQ1BMdzNBUGRMMWZRamwyQnFoY1BNTXJxXzU5TFN6eHVOS2ozSGcwVG44Q1JUaHhWdUFRRXU0QWxUa2Y2dkVsMmFJeFdZNmRHM1dQSUVKejdnSVVoRUNfTkw1Z21JWmFBVm52Vjk5SFp5X1ZJNXJEYVNiWHA2eWxxdVljU1JrbFBDallrUTh5NFlFWEE4Z1UyaENGWTRkaS1qS1E3ZA?oc=5",
    "published_at": "2026-07-05T08:09:44Z",
    "id": "social-1783284254430-1"
  },
  {
    "source": "News",
    "author": "The HALO Trust",
    "content": "Demining and risk education ongoing in Somalia.",
    "link": "https://news.google.com/rss/articles/CBMiakFVX3lxTE1WeUZwWWlwUm5ZdjZnTTJZYzRNMVNURHEzVzFmWlNkQ3d4MnB3ZlpISHE2cUs4T2pZcE1fSEdKUjl6eS1ndXNxVVRJemFBQjZvcTZYWTVtOUg1ZUVNYS1xeXNCUkVPblpFdkE?oc=5",
    "published_at": "2026-07-05T06:26:04Z",
    "id": "social-1783284254430-2"
  },
  {
    "source": "News",
    "author": "Dawan Africa",
    "content": "Somalia seeks to expand US partnership beyond security, President says.",
    "link": "https://news.google.com/rss/articles/CBMioAFBVV95cUxOVkxVekhsTDJqZDBWNk0wU05BS19GUkdfNEZLc0tScDRHdXBLaFdHRlhrcFFZZlpjNmdTRGNBZmVieWh3WW1DOTU5Q3FOLWhPQ081QXk1ZnhMcXExQzR5V3IwWFpCUGlQR1RVaWVvS3ZQZXRXamJfN1RtMWd3RWFIR1cwNUxtMndwMDF1cUlJMVg4Uk8xWXFHMm95Z3NNU3hv?oc=5",
    "published_at": "2026-07-05T15:48:20Z",
    "id": "social-1783284254430-3"
  },
  {
    "source": "X",
    "author": "@SomaliGuardian",
    "content": "Puntland bans Turkish fishing firm SOMTURK.",
    "link": "https://news.google.com/rss/articles/CBMiogFBVV95cUxQTXI2YXlIQVJ0MDluVUhlVzU1RHozX2xDOTY4N0p0WDg1TTZHQ1ZPUkQ4ZEgtdDJEdmdINHZycjRkcUFvbWFxQkE4UFpLTVFjNlg1Mkw5WG5kVlcxaXFyTnoxWTJCTm5VZUdNS1FBQnRUZ3VxNjRkQXNYZGJlWlM5RjF2dl9FeTltb2N3Qk5oRjIyWlg5MElOMVlUc2tWS2N6VWc?oc=5",
    "published_at": "2026-07-05T14:57:06Z",
    "id": "social-1783284254430-4"
  }
];
