// Auto-generated by fetchSocial.js (RSS + DeepSeek)

export interface SocialPost {
  id: string;
  source: 'X' | 'Facebook' | 'News';
  author: string;
  content: string;
  link: string;
  published_at: string;
}

export const socialFeed: SocialPost[] = [
  {
    "source": "News",
    "author": "UNSSC",
    "content": "How learning supported conflict prevention in Somalia – UNSSC report highlights education's role in peacebuilding.",
    "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxNQjFsNF8tM1M1VlE0YkNvU1JSWi1Sa29pVjNTdWxqVFpmU3R0Qk0yVFpLWC1QS24tejhTRmxmWDFSLTE0ak5LazBFOERtWHlkay1Za1d3VGZCa1pWYllFMDQxTmFFRzlYei1WcmliOHN6dWw0RVo5RUp0LVdqakhQRjNzaXg1STFmek9pcUJLNVQ?oc=5",
    "published_at": "2026-07-07T10:18:50Z",
    "id": "social-1783496022693-0"
  },
  {
    "source": "News",
    "author": "TRT Afrika",
    "content": "Why Somalia–Türkiye cooperation is a model for 21st-century foreign policy – A new partnership paradigm.",
    "link": "https://news.google.com/rss/articles/CBMiZEFVX3lxTFBGemczQml0ZGVHQ05WWDYzc0lrbTdoRkU0RGs5aTJmWHIxbzVrYVIwMlZ2YVRVZjVMOG5xLVdxM2JwdXJwWFFWc1c1MkNFOS15VHFzWjFJLUdzQmhOVXNPV0tIc2M?oc=5",
    "published_at": "2026-07-07T18:28:32Z",
    "id": "social-1783496022693-1"
  },
  {
    "source": "News",
    "author": "Hiiraan Online",
    "content": "Israeli military shipment arrives in Somalia under U.N. designation – Exclusive report on controversial cargo.",
    "link": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxNcXRXTi1Tc2lKZDRTeURPOFFka2l1YTA0X1pkMEFGdWF4X18wRVJPbGxGaHlOWUhMUTZhS0xOcHoxb3FjajFua1FXcjQ2MnE3d245ektDYnlRVVQ2S2Y3WjMydmd1a1RILUkwRFhlRkVTVmY1elhPaV9ZRFF0NUpuOUxHZnloZjJ3N3pNZmpDaWk1aFBjZG9yQmxvQVY3d012LWYzR0xhM2Z0OVgxR0huY29qUGJ4VnkzT3dGMEJHUFlxZw?oc=5",
    "published_at": "2026-07-08T05:51:25Z",
    "id": "social-1783496022693-2"
  },
  {
    "source": "News",
    "author": "Eurasia Review",
    "content": "Deadly Jihadist Groups Gain Momentum Across African Continent – Alarm over rising extremist activity.",
    "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxONUd3QlcwTFlZZTlROERmT2F4WUg4R0NaakNvOGd1T2V2ck5rZGxvdWU0RGR6clo3bUZuZ3JLQmJkN1lISV9MN2gybWN4aUNvYllkLUZXQjMzcXA4OFlGYnBlY3Y5LXRFTXM2LVJYTFRVSE03dXh5SV9EOHRLYUIwZTdRU2E1a3YwOGdoN3FuSUhaSm5YWUc1Y2M1Uy1IcEJma08w?oc=5",
    "published_at": "2026-07-07T23:52:40Z",
    "id": "social-1783496022693-3"
  },
  {
    "source": "News",
    "author": "Shipping Telegraph",
    "content": "Bulk carrier freed after piracy threat off Somalia; three ships remain in captivity – Maritime security update.",
    "link": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxPOTFJZkQyN0hibS0yMDhHMU9FT0ZFWkNoaGVCWm9sdHUwYVBwb0NzbWJGMV9DcDhWcGd1SGFYemI0cFYzTmVrUUp1MjRudXk1RkVBd0VyNVlEZkxCaGxaUTVZOGJSV0hiRUpNakUwR2I0U255OTVZNUQtRXhYYnRwcTEtQ2trZWdqTGdrSUNRNEhCSG10bEtfSzh2YnpLd184SHpPeGdvcUc4RzNiaXZ4LW5VbEU4X0haOUNhWGxYM19hYzVaZGtiY3RaVzVpSXFkMlE?oc=5",
    "published_at": "2026-07-08T01:01:40Z",
    "id": "social-1783496022693-4"
  },
  {
    "source": "X",
    "author": "@SomaliaSecurity",
    "content": "Political fragmentation in Somalia is fueling Al-Shabaab resurgence, warns Robert Lansing Institute. Urgent need for unified governance.",
    "link": "https://news.google.com/rss/articles/CBMipAFBVV95cUxQU1B6clhIYlFBUk41RDJuVXBFUTlwWVI4dDg2Zjl0TWotNlMwbFNWX2QtdU1sb2xVNk9ienpkd0N5ZTZGQm5EOGY5QTRqZWZmZFllTUwtalhxTWtyVlhkZFp4RTVBbU4xRC13NF9FRW9rUTdMT2FLYk81al9YVkc5dTlISmFtMHdBT1kzclFDdy01T3pXb2w5VDA2WS1mNXpoem9UOQ?oc=5",
    "published_at": "2026-07-07T15:27:44Z",
    "id": "social-1783484350525-0"
  },
  {
    "source": "News",
    "author": "Shipping Telegraph",
    "content": "Bulk carrier freed after piracy threat off Somalia; three ships remain in captivity. Maritime security remains a concern.",
    "link": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxPOTFJZkQyN0hibS0yMDhHMU9FT0ZFWkNoaGVCWm9sdHUwYVBwb0NzbWJGMV9DcDhWcGd1SGFYemI0cFYzTmVrUUp1MjRudXk1RkVBd0VyNVlEZkxCaGxaUTVZOGJSV0hiRUpNakUwR2I0U255OTVZNUQtRXhYYnRwcTEtQ2trZWdqTGdrSUNRNEhCSG10bEtfSzh2YnpLd184SHpPeGdvcUc4RzNiaXZ4LW5VbEU4X0haOUNhWGxYM19hYzVaZGtiY3RaVzVpSXFkMlE?oc=5",
    "published_at": "2026-07-08T01:01:40Z",
    "id": "social-1783484350525-1"
  },
  {
    "source": "News",
    "author": "TRT Afrika",
    "content": "Why Somalia–Türkiye cooperation is a model for 21st-century foreign policy. A strategic partnership strengthening regional stability.",
    "link": "https://news.google.com/rss/articles/CBMiZEFVX3lxTFBGemczQml0ZGVHQ05WWDYzc0lrbTdoRkU0RGs5aTJmWHIxbzVrYVIwMlZ2YVRVZjVMOG5xLVdxM2JwdXJwWFFWc1c1MkNFOS15VHFzWjFJLUdzQmhOVXNPV0tIc2M?oc=5",
    "published_at": "2026-07-07T18:28:32Z",
    "id": "social-1783484350525-2"
  },
  {
    "source": "Facebook",
    "author": "UNSSC",
    "content": "How learning supported conflict prevention in Somalia. UNSSC highlights education's role in building peace.",
    "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxNQjFsNF8tM1M1VlE0YkNvU1JSWi1Sa29pVjNTdWxqVFpmU3R0Qk0yVFpLWC1QS24tejhTRmxmWDFSLTE0ak5LazBFOERtWHlkay1Za1d3VGZCa1pWYllFMDQxTmFFRzlYei1WcmliOHN6dWw0RVo5RUp0LVdqakhQRjNzaXg1STFmek9pcUJLNVQ?oc=5",
    "published_at": "2026-07-07T10:18:50Z",
    "id": "social-1783484350525-3"
  },
  {
    "source": "News",
    "author": "Eurasia Review",
    "content": "Deadly Jihadist Groups Gain Momentum Across African Continent. Al-Shabaab among groups expanding influence.",
    "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxONUd3QlcwTFlZZTlROERmT2F4WUg4R0NaakNvOGd1T2V2ck5rZGxvdWU0RGR6clo3bUZuZ3JLQmJkN1lISV9MN2gybWN4aUNvYllkLUZXQjMzcXA4OFlGYnBlY3Y5LXRFTXM2LVJYTFRVSE03dXh5SV9EOHRLYUIwZTdRU2E1a3YwOGdoN3FuSUhaSm5YWUc1Y2M1Uy1IcEJma08w?oc=5",
    "published_at": "2026-07-07T23:52:40Z",
    "id": "social-1783484350525-4"
  },
  {
    "source": "News",
    "author": "Eurasia Review",
    "content": "Deadly Jihadist Groups Gain Momentum Across African Continent",
    "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxONUd3QlcwTFlZZTlROERmT2F4WUg4R0NaakNvOGd1T2V2ck5rZGxvdWU0RGR6clo3bUZuZ3JLQmJkN1lISV9MN2gybWN4aUNvYllkLUZXQjMzcXA4OFlGYnBlY3Y5LXRFTXM2LVJYTFRVSE03dXh5SV9EOHRLYUIwZTdRU2E1a3YwOGdoN3FuSUhaSm5YWUc1Y2M1Uy1IcEJma08w?oc=5",
    "published_at": "2026-07-07T23:52:40Z",
    "id": "social-1783469007827-0"
  },
  {
    "source": "News",
    "author": "Robert Lansing Institute",
    "content": "Somalia's Political Fragmentation Fuels Al-Shabaab's Resurgence",
    "link": "https://news.google.com/rss/articles/CBMipAFBVV95cUxQU1B6clhIYlFBUk41RDJuVXBFUTlwWVI4dDg2Zjl0TWotNlMwbFNWX2QtdU1sb2xVNk9ienpkd0N5ZTZGQm5EOGY5QTRqZWZmZFllTUwtalhxTWtyVlhkZFp4RTVBbU4xRC13NF9FRW9rUTdMT2FLYk81al9YVkc5dTlISmFtMHdBT1kzclFDdy01T3pXb2w5VDA2WS1mNXpoem9UOQ?oc=5",
    "published_at": "2026-07-07T15:27:44Z",
    "id": "social-1783469007827-1"
  },
  {
    "source": "News",
    "author": "Somali Guardian",
    "content": "Turkey holds Somalia government-opposition pre-talks as Puntland, Jubaland boycott ahead of key negotiations",
    "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxPOWVqZEZjOEVOYzJtSDdPa2dVRGFvc2hKTGVtVEhPbElnTG43LWMwOUlCeEhlS2ttMVhwOG5rOERVcjZDVW9CSW93c0Y4V1ktOWFUTFRNN3FBYjRSdDAxb3J0ZkwzV0J4OU14WTZtMm1Td0gwTlpwaHZwZUV1UlV5Tzd3RjBBV200QmpMMWQ1VVEwNEhOeGItb2JEeXl0UEpTaEhYNzNEbnh0V3M?oc=5",
    "published_at": "2026-07-07T17:24:23Z",
    "id": "social-1783469007827-2"
  },
  {
    "source": "News",
    "author": "TRT Afrika",
    "content": "Why Somalia–Türkiye cooperation is a model for 21st-century foreign policy",
    "link": "https://news.google.com/rss/articles/CBMiZEFVX3lxTFBGemczQml0ZGVHQ05WWDYzc0lrbTdoRkU0RGs5aTJmWHIxbzVrYVIwMlZ2YVRVZjVMOG5xLVdxM2JwdXJwWFFWc1c1MkNFOS15VHFzWjFJLUdzQmhOVXNPV0tIc2M?oc=5",
    "published_at": "2026-07-07T18:28:32Z",
    "id": "social-1783469007827-3"
  },
  {
    "source": "News",
    "author": "UNSSC",
    "content": "How learning supported conflict prevention in Somalia",
    "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxNQjFsNF8tM1M1VlE0YkNvU1JSWi1Sa29pVjNTdWxqVFpmU3R0Qk0yVFpLWC1QS24tejhTRmxmWDFSLTE0ak5LazBFOERtWHlkay1Za1d3VGZCa1pWYllFMDQxTmFFRzlYei1WcmliOHN6dWw0RVo5RUp0LVdqakhQRjNzaXg1STFmek9pcUJLNVQ?oc=5",
    "published_at": "2026-07-07T10:18:50Z",
    "id": "social-1783469007827-4"
  },
  {
    "source": "News",
    "author": "UNSSC",
    "content": "Learning programs in Somalia help prevent conflict, says UNSSC report. Education key to stability.",
    "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxNQjFsNF8tM1M1VlE0YkNvU1JSWi1Sa29pVjNTdWxqVFpmU3R0Qk0yVFpLWC1QS24tejhTRmxmWDFSLTE0ak5LazBFOERtWHlkay1Za1d3VGZCa1pWYllFMDQxTmFFRzlYei1WcmliOHN6dWw0RVo5RUp0LVdqakhQRjNzaXg1STFmek9pcUJLNVQ?oc=5",
    "published_at": "2026-07-07T10:18:50Z",
    "id": "social-1783462550348-0"
  },
  {
    "source": "X",
    "author": "@TRTAfrika",
    "content": "Somalia-Türkiye cooperation hailed as a model for 21st-century foreign policy. Strengthening ties in East Africa.",
    "link": "https://news.google.com/rss/articles/CBMiZEFVX3lxTFBGemczQml0ZGVHQ05WWDYzc0lrbTdoRkU0RGs5aTJmWHIxbzVrYVIwMlZ2YVRVZjVMOG5xLVdxM2JwdXJwWFFWc1c1MkNFOS15VHFzWjFJLUdzQmhOVXNPV0tIc2M?oc=5",
    "published_at": "2026-07-07T18:28:32Z",
    "id": "social-1783462550348-1"
  },
  {
    "source": "News",
    "author": "Somali Guardian",
    "content": "Turkey mediates Somalia talks as Puntland and Jubaland boycott. Pre-talks between government and opposition begin.",
    "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxPOWVqZEZjOEVOYzJtSDdPa2dVRGFvc2hKTGVtVEhPbElnTG43LWMwOUlCeEhlS2ttMVhwOG5rOERVcjZDVW9CSW93c0Y4V1ktOWFUTFRNN3FBYjRSdDAxb3J0ZkwzV0J4OU14WTZtMm1Td0gwTlpwaHZwZUV1UlV5Tzd3RjBBV200QmpMMWQ1VVEwNEhOeGItb2JEeXl0UEpTaEhYNzNEbnh0V3M?oc=5",
    "published_at": "2026-07-07T17:24:23Z",
    "id": "social-1783462550348-2"
  },
  {
    "source": "News",
    "author": "Bloomberg",
    "content": "Somalia backs India's objection to WhatsApp username switch, raising privacy concerns in tech policy.",
    "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxNSHk0NVRLUDNnY255cHV1cGlIcDBGek5DcmFnSjVMazF3eGdLYXBMclBQZ2l3T2NpWkhDejdWR0UtRXR2Ry1tNWFaWG5lYUdRaDRHUEhnOGU5VG1pcjVqQVB2VVBoUm5BTElhaXRtRkEwSU1iT241MzZpeTFrSi1MUExDbVBiM0RlREZxaFhEV01Sdkx1UlRJNFVfWUZPYzQ5ZkdtLURwVVlhUDZDdDJKOWRocDhJQQ?oc=5",
    "published_at": "2026-07-07T08:00:36Z",
    "id": "social-1783462550348-3"
  },
  {
    "source": "Facebook",
    "author": "Alpha News MN",
    "content": "Minnesota mayor visits Somalia over Fourth of July weekend, strengthening diaspora ties with homeland.",
    "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxQV1gyYnpKTm9WOHpUdU55eWM0TFF0ZGc2ZC1COWVwZVEwSHlrUTBjZ2JLTmlnaC1IU2JNTGMtYlRWdU16cGpkQXYzT0w5a21IS2hDNENmS2ZGLXRFeUNkczdGbnMzX1htY1JEWHdPTmlsc0tPeEc2SGRmYWxjQklqazlXb2t0SEVPcU10WElB?oc=5",
    "published_at": "2026-07-07T12:00:16Z",
    "id": "social-1783462550348-4"
  }
];
